/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercadodetodosa.vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import supermercadodetodosa.Producto;

/**
 *
 * @author Agustin Colongne
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form BusquedaPorPrecio
     */
    public BusquedaPorPrecio() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPrimerPrecio = new javax.swing.JTextField();
        jtSegundoPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaProductos = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Listado por Precio");

        jLabel2.setText("Entre : $");

        jtPrimerPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPrimerPrecioKeyReleased(evt);
            }
        });

        jtSegundoPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtSegundoPrecioKeyReleased(evt);
            }
        });

        jLabel3.setText("y");

        jtListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jtPrimerPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jtSegundoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPrimerPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSegundoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtSegundoPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSegundoPrecioKeyReleased
        // TODO add your handling code here:
        double primerPrecio;
        double segundoPrecio;

        borraFilas();

        if (jtPrimerPrecio.getText().isEmpty()) {
               primerPrecio = 0;
               jtPrimerPrecio.setText(0+"");
        }else{
            primerPrecio = Double.parseDouble(jtPrimerPrecio.getText());
        }

        

        if (jtSegundoPrecio.getText().isEmpty()) {
            segundoPrecio = primerPrecio;
        } else {
            segundoPrecio = Double.parseDouble(jtSegundoPrecio.getText());

        }

        for (Producto produc : Menu.listaProductos) {
            if (primerPrecio <= produc.getPrecio() && segundoPrecio >= produc.getPrecio()) {
                modelo.addRow(new Object[]{
                    produc.getCodigo(),
                    produc.getDescripcion(),
                    produc.getPrecio(),
                    produc.getStock(),});
            }

        }
    }//GEN-LAST:event_jtSegundoPrecioKeyReleased


    private void jtPrimerPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrimerPrecioKeyReleased
      
        double segudoPrecio = Double.parseDouble(jtSegundoPrecio.getText());
        double primerPrecio;
        if (!jtSegundoPrecio.getText().toString().isEmpty()) {
            primerPrecio = Double.parseDouble(jtPrimerPrecio.getText());
        }
    }//GEN-LAST:event_jtPrimerPrecioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListaProductos;
    private javax.swing.JTextField jtPrimerPrecio;
    private javax.swing.JTextField jtSegundoPrecio;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtListaProductos.setModel(modelo);
    }

    private void borraFilas() {
        int f = jtListaProductos.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
}
