/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercadodetodosa;

import javax.swing.JOptionPane;

/**
 *
 * @author Agustin Colongne
 */
public class CargarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargarProducto
     */
    public CargarProducto() {
        initComponents();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jcbRubro = new javax.swing.JComboBox<>();
        jbGuardar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtStock = new javax.swing.JTextField();
        jtDescripcion = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Codigo :");

        jLabel2.setText("Rubro");

        jLabel3.setText("Precio :");

        jLabel4.setText("Descripcion :");

        jLabel5.setText("Stock :");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtCodigo)
                    .addComponent(jcbRubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtDescripcion)
                    .addComponent(jtPrecio)
                    .addComponent(jtStock))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jbCancelar)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbCancelar))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        Categoria categoria;
        boolean validacion = true;
        int codigo;
        String rubro;
        String descripcion;
        double precio;
        int stock;

//        COMPRUEBA QUE TODOS LOS CAMPOS ESTEN LLENOS
        if (jtCodigo.getText().isEmpty()
                || jtDescripcion.getText().isEmpty()
                || jtPrecio.getText().isEmpty()
                || jtStock.getText().isEmpty()
                || jcbRubro.getSelectedItem().toString().equalsIgnoreCase("Elegir")) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios");

        } else {

            codigo = Integer.parseInt(jtCodigo.getText());
            rubro = (String) jcbRubro.getSelectedItem().toString();
            descripcion = (String) jtDescripcion.getText();
            precio = Double.parseDouble(jtPrecio.getText());
            stock = Integer.parseInt(jtStock.getText());

            if (rubro.equalsIgnoreCase("comestibles")) {
                categoria = Categoria.COMESTIBLES;
            } else if (rubro.equalsIgnoreCase("limpieza")) {
                categoria = Categoria.LIMPIEZA;
            } else {
                categoria = Categoria.PERFUMERIA;
            }
            for (Producto produc : Menu.listaProductos) {
                if (produc.getCodigo() == codigo) {
                    validacion = false;
                    break;

                } else {
                    validacion = true;
                }
            }

            if (validacion) {

                Producto producto = new Producto(codigo, descripcion, precio, stock, categoria);
                Menu.cargarProductos(producto);

                JOptionPane.showMessageDialog(this, "Se guardo con exito " + descripcion);
                borraCampos();
            } else {
                JOptionPane.showMessageDialog(this, "El codigo" + codigo + " ya esta en uso");
                jtCodigo.setText("");
            }

        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        borraCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbRubro;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables
    private void cargarComboBox() {
        jcbRubro.addItem(new String("Elegir"));
        jcbRubro.addItem(Categoria.COMESTIBLES.toString());
        jcbRubro.addItem(Categoria.LIMPIEZA.toString());
        jcbRubro.addItem(Categoria.PERFUMERIA.toString());

    }

    private void borraCampos() {
        jtCodigo.setText("");
        jtDescripcion.setText("");
        jtPrecio.setText("");
        jtStock.setText("");
        jcbRubro.setSelectedItem("Elegir");
    }
}
