/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercadodetodosa;

import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class EliminarProducto extends javax.swing.JInternalFrame {

    private Menu menu;

    /**
     * Creates new form EliminarProducto
     */
    public EliminarProducto(Menu menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio3 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtRubro = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(500, 486));
        setMinimumSize(new java.awt.Dimension(500, 486));
        setPreferredSize(new java.awt.Dimension(500, 486));

        escritorio3.setMaximumSize(new java.awt.Dimension(500, 486));
        escritorio3.setMinimumSize(new java.awt.Dimension(500, 486));

        jLabel1.setText("Codigo :");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Rubro");

        jtCodigo.setEditable(false);

        jLabel4.setText("Descripcion :");

        jtDescripcion.setEditable(false);

        jLabel3.setText("Precio :");

        jtPrecio.setEditable(false);

        jLabel5.setText("Stock :");

        jtStock.setEditable(false);

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        escritorio3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtStock, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtRubro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorio3Layout = new javax.swing.GroupLayout(escritorio3);
        escritorio3.setLayout(escritorio3Layout);
        escritorio3Layout.setHorizontalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDescripcion)
                    .addComponent(jtPrecio)
                    .addComponent(jtStock)
                    .addComponent(jtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jbBuscar)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorio3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jbEliminar)
                .addGap(80, 80, 80)
                .addComponent(jbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorio3Layout.setVerticalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(22, 22, 22)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminar)
                    .addComponent(jbCancelar))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtCodigo.setText("");
        jtDescripcion.setText("");
        jtPrecio.setText("");
        jtStock.setText("");
        jtRubro.setText("");
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se selecciono ningun producto para eliminar");
        } else {
            for (Producto producto : Menu.listaProductos) {
                if (producto.getCodigo() == Integer.parseInt(jtCodigo.getText())) {
                    Menu.listaProductos.remove(producto);
                    JOptionPane.showMessageDialog(this, "Se a eliminado con exito" + jtDescripcion.getText());

                    jtCodigo.setText("");
                    jtDescripcion.setText("");
                    jtPrecio.setText("");
                    jtStock.setText("");
                    jtRubro.setText("");
                    break;
                }
            }

        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        if (Menu.listaProductos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay productos cargados");
        } else {
            escritorio3.repaint();
            Tabla tabla = new Tabla(this);
            tabla.setVisible(true);
            menu.escritorio.add(tabla);
            menu.escritorio.moveToFront(tabla);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtRubro;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables

    void recuperardato(int codigo) {
        for (Producto producto : Menu.listaProductos) {
            if (producto.getCodigo() == codigo) {
                jtCodigo.setText(producto.getCodigo() + "");
                jtCodigo.setText(producto.getCodigo() + "");
                jtDescripcion.setText(producto.getDescripcion());
                jtPrecio.setText(producto.getPrecio() + "");
                jtStock.setText(producto.getStock() + "");
                if ("COMESTIBLES".equalsIgnoreCase(producto.getRubro().toString())) {
                    jtRubro.setText("COMESTIBLES");
                } else if (producto.getRubro().toString().equalsIgnoreCase("LIMPIEZA")) {
                    jtRubro.setText("LIMPIEZA");
                } else {
                    jtRubro.setText("PERFUMERIA");
                }
//                jtRubro.setSelectedItem(producto.getRubro());

                break;
            }
        }
    }
}
