/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercadodetodosa;

import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class EliminarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarProducto
     */
    public EliminarProducto() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio3 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jcbRubro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        escritorio3.setMaximumSize(new java.awt.Dimension(800, 600));
        escritorio3.setMinimumSize(new java.awt.Dimension(800, 600));
        escritorio3.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Codigo :");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Rubro");

        jtCodigo.setEditable(false);

        jLabel4.setText("Descripcion :");

        jLabel3.setText("Precio :");

        jLabel5.setText("Stock :");

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        escritorio3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jcbRubro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jtStock, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio3.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorio3Layout = new javax.swing.GroupLayout(escritorio3);
        escritorio3.setLayout(escritorio3Layout);
        escritorio3Layout.setHorizontalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtCodigo)
                    .addComponent(jcbRubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtDescripcion)
                    .addComponent(jtPrecio)
                    .addComponent(jtStock))
                .addGap(74, 74, 74)
                .addComponent(jbBuscar)
                .addGap(113, 113, 113))
            .addGroup(escritorio3Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jbEliminar)
                .addGap(163, 163, 163)
                .addComponent(jbCancelar)
                .addGap(0, 273, Short.MAX_VALUE))
        );
        escritorio3Layout.setVerticalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(26, 26, 26)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminar)
                    .addComponent(jbCancelar))
                .addGap(170, 170, 170))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(escritorio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:

        escritorio3.repaint();
        Tabla tabla = new Tabla(this);
        tabla.setVisible(true);
        escritorio3.add(tabla);
        escritorio3.moveToFront(tabla);
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se selecciono ningun producto para eliminar");
        } else {
            for (Producto producto : Menu.listaProductos) {
                if (producto.getCodigo() == Integer.parseInt(jtCodigo.getText())) {
                    Menu.listaProductos.remove(producto);
                    JOptionPane.showMessageDialog(this, "Se a eliminado con exito" + jtDescripcion.getText());

                    jtCodigo.setText("");
                    jtDescripcion.setText("");
                    jtPrecio.setText("");
                    jtStock.setText("");
                    break;
                }
            }

        }

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JComboBox<String> jcbRubro;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables
private void cargarCombo() {
        jcbRubro.addItem(new String("COMESTIBLES"));
        jcbRubro.addItem(new String("LIMPIEZA"));
        jcbRubro.addItem(new String("PERFUMERIA"));

    }

    void recuperardato(int codigo) {
        for (Producto producto : Menu.listaProductos) {
            if (producto.getCodigo() == codigo) {
                jtCodigo.setText(producto.getCodigo() + "");
                jtCodigo.setText(producto.getCodigo() + "");
                jtDescripcion.setText(producto.getDescripcion());
                jtPrecio.setText(producto.getPrecio() + "");
                jtStock.setText(producto.getStock() + "");
                if ("COMESTIBLES".equalsIgnoreCase(producto.getRubro().toString())) {
                    jcbRubro.setSelectedItem("COMESTIBLES");
                } else if (producto.getRubro().toString().equalsIgnoreCase("LIMPIEZA")) {
                    jcbRubro.setSelectedItem("LIMPIEZA");
                } else {
                    jcbRubro.setSelectedItem("PERFUMERIA");
                }
//                jcbRubro.setSelectedItem(producto.getRubro());

                break;
            }
        }
    }
}
